export const SUMMARY_QUALITY_ANALYSIS = "summaryQualityAnalysis"
export const SUMMARY_QUALITY_ANALYSIS_LABEL = "Summary Quality Analysis"
export const REPLY_QUALITY_ANALYSIS = "replyQualityAnalysis"
export const REPLY_QUALITY_ANALYSIS_LABEL = "Reply Quality Analysis"
export const SUGGESTIONS_QUALITY_ANALYSIS = "suggestionsQualityAnalysis"
export const SUGGESTIONS_QUALITY_ANALYSIS_LABEL = "Suggestions Quality Analysis"
export const COMMENTS_QUALITY_ANALYSIS = "commentsQualityAnalysis"
export const COMMENTS_QUALITY_ANALYSIS_LABEL = "Comments Quality Analysis"